import { chromium } from '@playwright/test'
const [out, theme = 'clean-light', node = 'api'] = process.argv.slice(2)
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 2 })
await page.goto(`http://localhost:5173/?d=architecture&theme=${theme}`)
await page.waitForSelector('[data-mp-ready="true"]', { timeout: 30000 })
await page.waitForSelector('.monaco-editor', { timeout: 20000 })
await page.getByRole('button', { name: 'Legend' }).click()
await page.getByRole('button', { name: 'Zoom in' }).click()
await page.getByRole('button', { name: 'Zoom in' }).click()
await page.locator(`.mp-node[data-node-id="${node}"]`).hover()
await page.waitForSelector('.mp-detail', { timeout: 5000 })
await page.waitForTimeout(350)
await page.locator('.mp-canvas-root').screenshot({ path: out })
console.log('saved', out)
await browser.close()
