import { chromium } from '@playwright/test'
const [out, theme = 'clean-light', tab = 'Themes'] = process.argv.slice(2)
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 2 })
await page.goto(`http://localhost:5173/?d=architecture&theme=${theme}`)
await page.waitForSelector('[data-mp-ready="true"]', { timeout: 30000 })
await page.waitForSelector('.monaco-editor', { timeout: 20000 })
await page.getByRole('button', { name: 'Theme editor' }).click()
await page.waitForSelector('.mp-theme-panel')
if (tab !== 'Themes') await page.getByRole('tab', { name: tab }).click()
await page.locator('.mp-node[data-node-id="api"]').click()
await page.waitForTimeout(400)
await page.screenshot({ path: out })
console.log('saved', out)
await browser.close()
